name: Veracode Test
on: [push, pull_request]

jobs:
  veracode-test:
    name: Node.js
    runs-on: self-hosted

    strategy:
      fail-fast: true
      # matrix:
      #   node-version: ["14.x"]

    steps:
      - name: Checkout https://github.com/${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      - name: Archive Release
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: |
          export SRCCLR_SCM_REF=${{ github.workflow }}
          export SRCCLR_SCM_REF_TYPE="branch"
          export SRCCLR_SCM_REV=${{ github.run_id }}
          export SRCCLR_SCM_TYPE="GITHUB"
          export EXTRA_ARGS='--update-advisor --uri-as-name' 
  
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s -- scan $EXTRA_ARGS
        continue-on-error: true